# Generated by Django 4.2.7 on 2026-01-20 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('admin', 'Admin'), ('salesman', 'Salesman'), ('customer', 'Customer')], default='customer', max_length=20),
        ),
    ]
