# Generated by Django 4.2.7 on 2026-03-29 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProfitReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stock_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('cash_balance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('receivables', models.DecimalField(decimal_places=2, max_digits=15)),
                ('payables', models.DecimalField(decimal_places=2, max_digits=15)),
                ('expenses_total', models.DecimalField(decimal_places=2, max_digits=15)),
                ('working_capital', models.DecimalField(decimal_places=2, max_digits=15)),
                ('net_profit_loss', models.DecimalField(decimal_places=2, max_digits=15)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
