# Generated by Django 4.2.7 on 2026-02-27 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('cash', 'Cash (Upfront/COD)'), ('credit', 'Credit (Net-30)')], default='credit', max_length=10),
        ),
    ]
