# Generated by Django 4.2.7 on 2026-02-27 20:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_payment_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, unique=True)),
                ('total_cash', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_credit', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
            ],
        ),
    ]
