# Generated by Django 4.2.7 on 2026-03-29 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashaccount',
            name='total_credit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='cashaccount',
            name='total_debit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
