# Generated by Django 4.2.7 on 2026-03-29 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_cashaccount_total_credit_cashaccount_total_debit'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashaccount',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='expensetransaction',
            name='cash_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paid_expenses', to='accounting.cashaccount'),
        ),
    ]
