# Generated by Django 6.0.6 on 2026-06-22 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0003_alter_product_sku_alter_purchase_purchase_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_sold', models.PositiveIntegerField()),
                ('sale_date', models.DateField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_synthetic', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_records', to='inventory.product')),
            ],
            options={
                'verbose_name': 'Sale Record',
                'verbose_name_plural': 'Sale Records',
                'ordering': ['-sale_date'],
            },
        ),
        migrations.CreateModel(
            name='ForecastResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_date', models.DateField()),
                ('predicted_quantity', models.FloatField()),
                ('lower_bound', models.FloatField(default=0)),
                ('upper_bound', models.FloatField(default=0)),
                ('model_used', models.CharField(default='WMA', max_length=50)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='inventory.product')),
            ],
            options={
                'verbose_name': 'Forecast Result',
                'verbose_name_plural': 'Forecast Results',
                'ordering': ['forecast_date'],
                'unique_together': {('product', 'forecast_date')},
            },
        ),
    ]
